# See http://www.appveyor.com/docs/appveyor-yml for many more options
before_build:
 nuget restore

before_test:
- ps: |
    $ErrorActionPreference = 'Stop';
    $sqlServerUrl = "$($env:downloadUrl)/SQLServer2016-x64-ENU.exe"
    $sqlServerUrlBox = "$($env:downloadUrl)/SQLServer2016-x64-ENU.box"
    # instance name express to be able to switch easy between express and eval
    $sqlServerSilentArgs = "/IACCEPTSQLSERVERLICENSETERMS /Q /ACTION=install /INSTANCEID=SQLEXPRESS /INSTANCENAME=SQLEXPRESS /UPDATEENABLED=FALSE /FEATURES=SQLEngine /SQLSYSADMINACCOUNTS=`"BUILTIN\Administrators`""
    $tempDir = Join-Path (Get-Item $env:TEMP).FullName "sql2016Eval"
    if ((Test-Path $tempDir) -eq $false) { New-Item -ItemType Directory -Path $tempDir}
    $fileFullPath = "$tempDir\SQLServer.exe"
    $fileFullPathBox = "$tempDir\SQLServer.box"
    Write-Host "Downloading SQL Server..." (Get-Date).DateTime
    (New-Object Net.WebClient).DownloadFile($sqlServerUrl , $fileFullPath)
    (New-Object Net.WebClient).DownloadFile($sqlServerUrlBox , $fileFullPathBox)
    Write-Host "Extracting SQL Server..." (Get-Date).DateTime
    $extractPath = "$tempDir\SQLEXPR"
    Start-Process "$fileFullPath" "/Q /x:`"$extractPath`"" -Wait
    Write-Host "Installing SQL Server..." (Get-Date).DateTime
    $setupPath = "$extractPath\setup.exe"
    Start-Process $setupPath "$sqlServerSilentArgs" -Wait
    Write-Host "SQL Server Installation completed" (Get-Date).DateTime
    # Downloading and installing Power BI Report Server
    $pbiServerUrl = $env:pbirsDownloadUrl
    $pbiServerTempDir = Join-Path (Get-Item $env:TEMP).FullName "PBIServer"
    if ((Test-Path $pbiServerTempDir) -eq $false) { New-Item -ItemType Directory -Path $pbiServerTempDir }
    $pbiServerFileFullPath = "$pbiServerTempDir\PowerBIReportServer.exe"
    $pbiServerSilentArgs = "/Q /NORESTART IACCEPTLICENSETERMS=true"
    try {
        Write-Host "Downloading Power BI Report Server..." (Get-Date).DateTime
        (New-Object Net.WebClient).DownloadFile($pbiServerUrl , $pbiServerFileFullPath)
        Write-Host "Installing Power BI Report Server..." (Get-Date).DateTime
        
        Start-Process $pbiServerFileFullPath "$pbiServerSilentArgs" -Wait
        Write-Host "Power BI Report Server Installation completed" (Get-Date).DateTime
    } catch {
        Write-Error "Exception occurred while downloading Power BI Report Server: $_.Exception.Message"
        throw
    }
    # Configuring Power BI Report Server
    Write-Host "Downloading Reporting Services tools..." (Get-Date).DateTime
    if (!(Test-Path $profile)) {
        Write-Host "No profile found! Creating a profile!"
        new-item -path $profile -itemtype file -force
    }
    $rsToolsLocalpath = $(Join-Path -Path (Split-Path -Path $profile) -ChildPath '\Modules\ReportingServicesTools')
    $rsToolsUrl = 'https://github.com/Microsoft/ReportingServicesTools/archive/master.zip'
    $temp = (Get-Item $env:TEMP).FullName
    $rsToolsZipfile = Join-Path (Get-Item $env:TEMP).FullName "ReportingServicesTools.zip"
    if (!(Test-Path -Path $rsToolsLocalpath)) {
        try {
            Write-Host "Creating directory: $rsToolsLocalpath"
            New-Item -Path $rsToolsLocalpath -ItemType Directory | Out-Null
        } catch {
            throw "Can't create $rsToolsLocalpath. You may need to Run as Administrator"
        }
    } else {
        try {
            Write-Host "Deleting previously installed module"
            Remove-Item -Path "$rsToolsLocalpath\*" -Force -Recurse
        } catch {
            throw "Can't delete $rsToolsLocalpath. You may need to Run as Administrator"
        }
    }
    Write-Host "Downloading archive from github"
    try {
        Invoke-WebRequest $rsToolsUrl -OutFile $rsToolsZipfile
    } catch {
        #try with default proxy and usersettings
        Write-Host "Probably using a proxy for internet access, trying default proxy settings"
        (New-Object System.Net.WebClient).Proxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
        Invoke-WebRequest $rsToolsUrl -OutFile $rsToolsZipfile
    }
    # Unblock if there's a block
    Unblock-File $rsToolsZipfile -ErrorAction SilentlyContinue
    Write-Host "Unzipping"

    # Keep it backwards compatible
    $shell = New-Object -COM Shell.Application
    $zipPackage = $shell.NameSpace($rsToolsZipfile)
    $destinationFolder = $shell.NameSpace($temp)
    $destinationFolder.CopyHere($zipPackage.Items())

    Write-Host "Cleaning up"
    Move-Item -Path "$temp\ReportingServicesTools-master\*" $rsToolsLocalpath
    Remove-Item -Path "$temp\ReportingServicesTools-master"
    Remove-Item -Path $rsToolsZipfile

    Write-Host "Done!"
    if ((Get-Command -Module ReportingServicesTools).count -eq 0) { Import-Module "$path\src\ReportingServicesTools.psd1" -Force }
    if ((Get-Command -Module ReportingServicesTools).count -eq 0) { throw 'Unable to import ReportingServicesTools Module' }

    Write-Host "Configuring Report Server database..." (Get-Date).DateTime
    Set-RsDatabase -ReportServerInstance PBIRS -ReportServerVersion 14 -DatabaseServerName SQLEXPRESS -DatabaseName ReportServer -DatabaseCredentialType ServiceAccount
    Write-Host "Configuring Report Server URL for Server..." (Get-Date).DateTime
    $rsConfigObject = New-RsConfigurationSettingObject -ReportServerInstance PBIRS -ReportServerVersion 14
    $rsConfigObject.SetVirtualDirectory('ReportServerWebService', 'ReportServer', 1033)
    $rsConfigObject.ReserveUrl('ReportServerWebService', 'http://+:80', 1033)
    Write-Host "Configuring Report Server URL for Portal..." (Get-Date).DateTime
    $rsConfigObject.SetVirtualDirectory('ReportServerWebApp', 'Reports', 1033)
    $rsConfigObject.ReserveUrl('ReportServerWebApp', 'http://+:80', 1033)
    Write-Host "Restarting Power BI Report Server Service..."(Get-Date).DateTime
    Stop-Service PowerBIReportServer
    Start-Service PowerBIReportServer
    Write-Host "Power BI Report Server configured successfully..."(Get-Date).DateTime

test_script:
 TestForCI.cmd